In [ ]:
# Diabetes DataSet

In [1]:
from sklearn.datasets import load_diabetes
X,y=load_diabetes(return_X_y=True)

In [2]:
randomseed=42

In [3]:
import pandas as pd
X=pd.DataFrame(X)
y=pd.DataFrame(y)
X.head()

,0,1,2,3,4,5,6,7,8,9
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204
2,0.085299,0.050680,0.044451,-0.005671,-0.045599,-0.034194,-0.032356,-0.002592,0.002864,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022692,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641

In [4]:
data=load_diabetes()

In [5]:
data

{'DESCR': '.. _diabetes_dataset:\n\nDiabetes dataset\n----------------\n\nTen baseline variables, age, sex, body mass index, average blood\npressure, and six blood serum measurements were obtained for each of n =\n442 diabetes patients, as well as the response of interest, a\nquantitative measure of disease progression one year after baseline.\n\n**Data Set Characteristics:**\n\n  :Number of Instances: 442\n\n  :Number of Attributes: First 10 columns are numeric predictive values\n\n  :Target: Column 11 is a quantitative measure of disease progression one year after baseline\n\n  :Attribute Information:\n      - age     age in years\n      - sex\n      - bmi     body mass index\n      - bp      average blood pressure\n      - s1      tc, total serum cholesterol\n      - s2      ldl, low-density lipoproteins\n      - s3      hdl, high-density lipoproteins\n      - s4      tch, total cholesterol / HDL\n      - s5      ltg, possibly log of serum triglycerides level\n      - s6      glu, blood sugar level\n\nNote: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).\n\nSource URL:\nhttps://www4.stat.ncsu.edu/~boos/var.select/diabetes.html\n\nFor more information see:\nBradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani (2004) "Least Angle Regression," Annals of Statistics (with discussion), 407-499.\n(https://web.stanford.edu/~hastie/Papers/LARS/LeastAngle_2002.pdf)',
 'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990842, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06832974, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286377, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04687948,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452837, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00421986,  0.00306441]]),
 'data_filename': 'diabetes_data.csv.gz',
 'data_module': 'sklearn.datasets.data',
 'feature_names': ['age',
  'sex',
  'bmi',
  'bp',
  's1',
  's2',
  's3',
  's4',
  's5',
  's6'],
 'frame': None,
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
        128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
        150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
        200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
         42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
         83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
        104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
        173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
        107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
         60., 174., 259., 178., 128.,  96., 126., 288.,  88., 292.,  71.,
        197., 186.,  25.,  84.,  96., 195.,  53., 217., 172., 131., 214.,
         59.,  70., 220., 268., 152.,  47.,  74., 295., 101., 151., 127.,
        237., 225.,  81., 151., 107.,  64., 138., 185., 265., 101., 137.,
        143., 141.,  79., 292., 178.,  91., 116.,  86., 122.,  72., 129.,
        142.,  90., 158.,  39., 196., 222., 277.,  99., 196., 202., 155.,
         77., 191.,  70.,  73.,  49.,  65., 263., 248., 296., 214., 185.,
         78.,  93., 252., 150.,  77., 208.,  77., 108., 160.,  53., 220.,
        154., 259.,  90., 246., 124.,  67.,  72., 257., 262., 275., 177.,
         71.,  47., 187., 125.,  78.,  51., 258., 215., 303., 243.,  91.,
        150., 310., 153., 346.,  63.,  89.,  50.,  39., 103., 308., 116.,
        145.,  74.,  45., 115., 264.,  87., 202., 127., 182., 241.,  66.,
         94., 283.,  64., 102., 200., 265.,  94., 230., 181., 156., 233.,
         60., 219.,  80.,  68., 332., 248.,  84., 200.,  55.,  85.,  89.,
         31., 129.,  83., 275.,  65., 198., 236., 253., 124.,  44., 172.,
        114., 142., 109., 180., 144., 163., 147.,  97., 220., 190., 109.,
        191., 122., 230., 242., 248., 249., 192., 131., 237.,  78., 135.,
        244., 199., 270., 164.,  72.,  96., 306.,  91., 214.,  95., 216.,
        263., 178., 113., 200., 139., 139.,  88., 148.,  88., 243.,  71.,
         77., 109., 272.,  60.,  54., 221.,  90., 311., 281., 182., 321.,
         58., 262., 206., 233., 242., 123., 167.,  63., 197.,  71., 168.,
        140., 217., 121., 235., 245.,  40.,  52., 104., 132.,  88.,  69.,
        219.,  72., 201., 110.,  51., 277.,  63., 118.,  69., 273., 258.,
         43., 198., 242., 232., 175.,  93., 168., 275., 293., 281.,  72.,
        140., 189., 181., 209., 136., 261., 113., 131., 174., 257.,  55.,
         84.,  42., 146., 212., 233.,  91., 111., 152., 120.,  67., 310.,
         94., 183.,  66., 173.,  72.,  49.,  64.,  48., 178., 104., 132.,
        220.,  57.]),
 'target_filename': 'diabetes_target.csv.gz'}

In [6]:
df=pd.concat([X,y],axis=1)
df

,0,1,2,3,4,5,6,7,8,9,0
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005671,-0.045599,-0.034194,-0.032356,-0.002592,0.002864,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022692,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018118,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017282,-0.037344,-0.013840,-0.024993,-0.011080,-0.046879,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044528,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081414,0.083740,0.027809,0.173816,-0.039493,-0.004220,0.003064,57.0

In [7]:
df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
0    0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
X_train.shape

(353, 10)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=randomseed)
X_test.shape

(89, 10)

In [12]:
from sklearn.linear_model import LinearRegression
model_lr=LinearRegression()
model_lr.fit(X_train,y_train)

LinearRegression()

In [13]:
X_test

,0,1,2,3,4,5,6,7,8,9
287,0.045341,-0.044642,-0.006206,-0.015999,0.125019,0.125198,0.019187,0.034309,0.032433,-0.005220
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022512,-0.021788
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084495,-0.017646
321,0.096197,-0.044642,0.051996,0.079254,0.054845,0.036577,-0.076536,0.141322,0.098646,0.061054
73,0.012648,0.050680,-0.020218,-0.002228,0.038334,0.053174,-0.006584,0.034309,-0.005145,-0.009362
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005671,-0.007073,-0.019476,0.041277,-0.039493,-0.003304,0.007207
90,0.012648,-0.044642,-0.025607,-0.040099,-0.030464,-0.045155,0.078093,-0.076395,-0.072128,0.011349
57,-0.027310,-0.044642,-0.063330,-0.050428,-0.089630,-0.104340,0.052322,-0.076395,-0.056158,-0.067351
391,-0.023677,-0.044642,-0.069797,-0.064199,-0.059359,-0.050478,0.019187,-0.039493,-0.089137,-0.050783
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025952,-0.054925

In [14]:
y_test

         0
287  219.0
211   70.0
72   202.0
321  230.0
73   111.0
..     ...
255  153.0
90    98.0
57    37.0
391   63.0
24   184.0

[89 rows x 1 columns]

In [15]:
y_pred=model_lr.predict(X_test[0:])

In [16]:
y_pred

array([[139.5483133 ],
       [179.52030578],
       [134.04133298],
       [291.41193598],
       [123.78723656],
       [ 92.17357677],
       [258.23409704],
       [181.33895238],
       [ 90.22217862],
       [108.63143298],
       [ 94.13938654],
       [168.43379636],
       [ 53.50669663],
       [206.63040068],
       [100.13238561],
       [130.66881649],
       [219.53270758],
       [250.78291772],
       [196.36682356],
       [218.57497401],
       [207.35002447],
       [ 88.48361667],
       [ 70.43428801],
       [188.95725301],
       [154.88720039],
       [159.35957695],
       [188.31587948],
       [180.38835506],
       [ 47.98988446],
       [108.97514644],
       [174.78080029],
       [ 86.36598906],
       [132.95890535],
       [184.5410226 ],
       [173.83298051],
       [190.35863287],
       [124.41740796],
       [119.65426903],
       [147.95402494],
       [ 59.05311211],
       [ 71.62636914],
       [107.68722902],
       [165.45544477],
       [155.00784964],
       [171.04558668],
       [ 61.45763075],
       [ 71.66975626],
       [114.96330486],
       [ 51.57808027],
       [167.57781958],
       [152.52505798],
       [ 62.95827693],
       [103.49862017],
       [109.20495627],
       [175.63844013],
       [154.60247734],
       [ 94.41476124],
       [210.74244148],
       [120.25601864],
       [ 77.61590087],
       [187.93503183],
       [206.49543321],
       [140.63018684],
       [105.59463059],
       [130.704246  ],
       [202.18650868],
       [171.1330116 ],
       [164.91246096],
       [124.72637597],
       [144.81210187],
       [181.99631481],
       [199.41234515],
       [234.21402489],
       [145.96053305],
       [ 79.86349114],
       [157.36828831],
       [192.74737754],
       [208.8980067 ],
       [158.58505486],
       [206.0226849 ],
       [107.47978402],
       [140.93428553],
       [ 54.81856678],
       [ 55.92807758],
       [115.00974554],
       [ 78.95886675],
       [ 81.55731377],
       [ 54.3774778 ],
       [166.25477778]])

In [19]:
from sklearn.tree import DecisionTreeRegressor
model_dt=DecisionTreeRegressor()
model_dt.fit(X_train,y_train)

DecisionTreeRegressor()

In [20]:
y_pred=model_dt.predict(X_test)
y_pred

array([190., 166., 170., 268., 139.,  97., 233., 262., 206., 197.,  77.,
       200.,  72., 220.,  88.,  60., 317., 306., 293., 163., 141.,  65.,
        49., 150.,  85., 121., 281., 162.,  59., 230., 200.,  50., 172.,
       283., 167., 180.,  94.,  74., 120.,  96.,  59.,  85., 219., 131.,
       170.,  75.,  31., 170.,  59., 179., 142.,  72., 144., 179., 292.,
       141.,  53., 198.,  59.,  57.,  67., 141., 142.,  85., 124., 178.,
        58.,  69., 150., 206., 206., 281., 241., 162., 132., 229., 217.,
       178., 109., 229.,  49.,  25.,  59.,  45.,  49.,  52.,  74.,  74.,
       147.])

In [21]:
X_test

,0,1,2,3,4,5,6,7,8,9
287,0.045341,-0.044642,-0.006206,-0.015999,0.125019,0.125198,0.019187,0.034309,0.032433,-0.005220
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022512,-0.021788
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084495,-0.017646
321,0.096197,-0.044642,0.051996,0.079254,0.054845,0.036577,-0.076536,0.141322,0.098646,0.061054
73,0.012648,0.050680,-0.020218,-0.002228,0.038334,0.053174,-0.006584,0.034309,-0.005145,-0.009362
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005671,-0.007073,-0.019476,0.041277,-0.039493,-0.003304,0.007207
90,0.012648,-0.044642,-0.025607,-0.040099,-0.030464,-0.045155,0.078093,-0.076395,-0.072128,0.011349
57,-0.027310,-0.044642,-0.063330,-0.050428,-0.089630,-0.104340,0.052322,-0.076395,-0.056158,-0.067351
391,-0.023677,-0.044642,-0.069797,-0.064199,-0.059359,-0.050478,0.019187,-0.039493,-0.089137,-0.050783
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025952,-0.054925

In [ ]:
#K-fold

In [30]:
from sklearn.datasets import load_diabetes
X1,y1=load_diabetes(return_X_y=True)

In [31]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
for train, test in kf.split(X1, y1):
  Xtrain, Xtest = X1[train], X1[test] 
  ytrain, ytest = y1[train], y1[test]

In [27]:
X_test

,0,1,2,3,4,5,6,7,8,9
287,0.045341,-0.044642,-0.006206,-0.015999,0.125019,0.125198,0.019187,0.034309,0.032433,-0.005220
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022512,-0.021788
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084495,-0.017646
321,0.096197,-0.044642,0.051996,0.079254,0.054845,0.036577,-0.076536,0.141322,0.098646,0.061054
73,0.012648,0.050680,-0.020218,-0.002228,0.038334,0.053174,-0.006584,0.034309,-0.005145,-0.009362
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005671,-0.007073,-0.019476,0.041277,-0.039493,-0.003304,0.007207
90,0.012648,-0.044642,-0.025607,-0.040099,-0.030464,-0.045155,0.078093,-0.076395,-0.072128,0.011349
57,-0.027310,-0.044642,-0.063330,-0.050428,-0.089630,-0.104340,0.052322,-0.076395,-0.056158,-0.067351
391,-0.023677,-0.044642,-0.069797,-0.064199,-0.059359,-0.050478,0.019187,-0.039493,-0.089137,-0.050783
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025952,-0.054925

In [32]:
from sklearn.datasets import load_diabetes
X2,y2=load_diabetes(return_X_y=True)

In [33]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
for train, test in kf.split(X2, y2):
  Xtrain, Xtest = X2[train], X2[test] 
  ytrain, ytest = y2[train], y2[test]

In [34]:
X_test

,0,1,2,3,4,5,6,7,8,9
287,0.045341,-0.044642,-0.006206,-0.015999,0.125019,0.125198,0.019187,0.034309,0.032433,-0.005220
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022512,-0.021788
72,0.063504,0.050680,-0.004050,-0.012556,0.103003,0.048790,0.056003,-0.002592,0.084495,-0.017646
321,0.096197,-0.044642,0.051996,0.079254,0.054845,0.036577,-0.076536,0.141322,0.098646,0.061054
73,0.012648,0.050680,-0.020218,-0.002228,0.038334,0.053174,-0.006584,0.034309,-0.005145,-0.009362
...,...,...,...,...,...,...,...,...,...,...
255,0.001751,-0.044642,-0.065486,-0.005671,-0.007073,-0.019476,0.041277,-0.039493,-0.003304,0.007207
90,0.012648,-0.044642,-0.025607,-0.040099,-0.030464,-0.045155,0.078093,-0.076395,-0.072128,0.011349
57,-0.027310,-0.044642,-0.063330,-0.050428,-0.089630,-0.104340,0.052322,-0.076395,-0.056158,-0.067351
391,-0.023677,-0.044642,-0.069797,-0.064199,-0.059359,-0.050478,0.019187,-0.039493,-0.089137,-0.050783
24,-0.063635,-0.044642,0.035829,-0.022885,-0.030464,-0.018850,-0.006584,-0.002592,-0.025952,-0.054925

In [36]:
from sklearn.linear_model import LinearRegression
model_lr=LinearRegression()
model_lr.fit(Xtrain,ytrain)

LinearRegression()

In [37]:
y_pred=model_lr.predict(Xtest)
y_pred

array([191.42755525, 133.04877448,  91.97677251, 198.85251886,
        54.98917741, 173.71496126, 196.45853504, 120.51068765,
       233.23043101, 163.51698175, 161.25297652, 163.87635245,
       253.65571515, 255.59408899, 197.81068341, 185.44645028,
        60.136369  , 194.75215437, 109.34153649, 143.03292209,
       127.92878888, 176.04394067, 209.93507631, 166.33590143,
       162.17984648, 137.52983423, 174.20311213,  74.27388858,
       249.47602759, 113.96862315, 108.93850616, 138.30775304,
       110.87297284,  95.73780182, 159.50300881,  75.56060774,
       254.52713294,  57.2151258 ,  99.57030731, 101.80895415,
       261.24938284, 168.81352273,  64.20043431, 183.10714025,
       169.90316133, 187.00854392, 184.8058785 ,  90.37629602,
       148.74592464, 251.58873636, 198.12771061, 279.87044377,
        51.41253122, 175.31773735, 201.50171976, 170.2097595 ,
       155.29608618, 152.87506316, 232.74795372, 122.87668768,
       163.18303141, 172.87883213, 225.2838219 , 152.36655417,
        99.61312765,  84.10835367, 142.05105494, 189.88328509,
       195.33173077, 150.02075001, 171.08885186, 113.07589976,
       161.34647259, 130.97680332, 257.19688034, 100.36438648,
       116.38378469, 121.47938471, 219.42669778,  61.97294807,
       132.7329999 , 120.51818799,  54.18385298, 190.31596542,
       102.82568871, 121.90793261, 209.99779855,  53.80693157])

In [38]:
model_dt.fit(Xtrain, ytrain)

DecisionTreeRegressor()

In [39]:
y_pred=model_dt.predict(Xtest)
y_pred

array([268., 162., 216.,  99.,  89., 107.,  70.,  61., 341., 292.,  92.,
       246., 220., 180., 268.,  78.,  96., 152.,  53.,  71., 185., 280.,
       259., 191., 292., 137., 225., 162., 265.,  79., 219., 150., 153.,
       172., 214.,  97., 295.,  55., 128., 144., 152., 206.,  71.,  52.,
       310., 170., 263.,  39.,  89., 265., 263., 308.,  85., 279., 275.,
       222., 137., 145., 279.,  72., 196., 191., 178., 172.,  59., 113.,
        83., 249., 259.,  89., 292.,  65., 268.,  49., 243., 168.,  84.,
        75., 268.,  65.,  61.,  42.,  77., 214.,  51.,  49., 137.,  96.])